set_property SRC_FILE_INFO {cfile:D:/Work/Embedded/FPGA/Program/MAC/prj/ethernet_test/rgmii_ethernet/eth_test.srcs/constrs_1/new/top.xdc rfile:../eth_test.srcs/constrs_1/new/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -reset_path -from [get_clocks sys_clk_p] -to [get_clocks e1_rx_clk]
set_property src_info {type:XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -reset_path -from [get_clocks sys_clk_p] -to [get_clocks e2_rx_clk]
set_property src_info {type:XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -reset_path -from [get_clocks sys_clk_p] -to [get_clocks e3_rx_clk]
set_property src_info {type:XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -reset_path -from [get_clocks sys_clk_p] -to [get_clocks e4_rx_clk]
