# ############## clock define#######################
set_property PACKAGE_PIN Y9 [get_ports sys_clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk_in]
create_clock -period 20.000 -name sys_clk_in [get_ports sys_clk_in]
# ##############reset key define####################
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN A17 [get_ports rst_n]
# ##############LED define##########################
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN A16 [get_ports {led[1]}]
set_property PACKAGE_PIN R7 [get_ports {led[0]}]
# #########################ethernet1###################
set_property IOSTANDARD LVCMOS33 [get_ports e1_reset]
set_property IOSTANDARD LVCMOS33 [get_ports e1_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports e1_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports {e1_rrxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e1_rrxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e1_rrxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e1_rrxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e1_rtxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e1_rtxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e1_rtxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e1_rtxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports e1_rrxc]
set_property IOSTANDARD LVCMOS33 [get_ports e1_rrxdv]
set_property IOSTANDARD LVCMOS33 [get_ports e1_rtxc]
set_property IOSTANDARD LVCMOS33 [get_ports e1_rtxen]

set_property PACKAGE_PIN J17 [get_ports e1_mdc]
set_property PACKAGE_PIN J16 [get_ports e1_mdio]
set_property PACKAGE_PIN L19 [get_ports e1_reset]
set_property PACKAGE_PIN K19 [get_ports e1_rrxc]
set_property PACKAGE_PIN K20 [get_ports e1_rrxdv]
set_property PACKAGE_PIN R21 [get_ports e1_rtxc]
set_property PACKAGE_PIN R20 [get_ports e1_rtxen]
set_property PACKAGE_PIN J18 [get_ports {e1_rrxd[0]}]
set_property PACKAGE_PIN K18 [get_ports {e1_rrxd[1]}]
set_property PACKAGE_PIN J15 [get_ports {e1_rrxd[2]}]
set_property PACKAGE_PIN K15 [get_ports {e1_rrxd[3]}]
set_property PACKAGE_PIN N17 [get_ports {e1_rtxd[0]}]
set_property PACKAGE_PIN N18 [get_ports {e1_rtxd[1]}]
set_property PACKAGE_PIN N19 [get_ports {e1_rtxd[2]}]
set_property PACKAGE_PIN N20 [get_ports {e1_rtxd[3]}]

create_clock -period 8.000 -name e1_rrxc [get_ports e1_rrxc]
set_false_path -reset_path -from [get_clocks sys_clk_in] -to [get_clocks e1_rrxc]

set_property SLEW FAST [get_ports {e1_rtxd[*]}]
set_property SLEW FAST [get_ports e1_rtxen]
set_property SLEW FAST [get_ports e1_rtxc]
# #########################ethernet2###################
set_property IOSTANDARD LVCMOS33 [get_ports e2_reset]
set_property IOSTANDARD LVCMOS33 [get_ports e2_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports e2_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports {e2_rrxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e2_rrxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e2_rrxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e2_rrxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e2_rtxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e2_rtxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e2_rtxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e2_rtxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports e2_rrxc]
set_property IOSTANDARD LVCMOS33 [get_ports e2_rrxdv]
set_property IOSTANDARD LVCMOS33 [get_ports e2_rtxc]
set_property IOSTANDARD LVCMOS33 [get_ports e2_rtxen]

set_property PACKAGE_PIN M20 [get_ports e2_mdc]
set_property PACKAGE_PIN T17 [get_ports e2_mdio]
set_property PACKAGE_PIN T16 [get_ports e2_reset]
set_property PACKAGE_PIN M19 [get_ports e2_rrxc]
set_property PACKAGE_PIN P17 [get_ports e2_rrxdv]
set_property PACKAGE_PIN K16 [get_ports e2_rtxc]
set_property PACKAGE_PIN M22 [get_ports e2_rtxen]
set_property PACKAGE_PIN P18 [get_ports {e2_rrxd[0]}]
set_property PACKAGE_PIN P22 [get_ports {e2_rrxd[1]}]
set_property PACKAGE_PIN N22 [get_ports {e2_rrxd[2]}]
set_property PACKAGE_PIN M21 [get_ports {e2_rrxd[3]}]
set_property PACKAGE_PIN L18 [get_ports {e2_rtxd[0]}]
set_property PACKAGE_PIN L22 [get_ports {e2_rtxd[1]}]
set_property PACKAGE_PIN L21 [get_ports {e2_rtxd[2]}]
set_property PACKAGE_PIN L16 [get_ports {e2_rtxd[3]}]

create_clock -period 8.000 -name e2_rrxc [get_ports e2_rrxc]
set_false_path -reset_path -from [get_clocks sys_clk_in] -to [get_clocks e2_rrxc]

set_property SLEW FAST [get_ports {e2_rtxd[*]}]
set_property SLEW FAST [get_ports e2_rtxen]
set_property SLEW FAST [get_ports e2_rtxc]
# #########################ethernet3###################
set_property IOSTANDARD LVCMOS33 [get_ports {e3_rrxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e3_rrxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e3_rrxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e3_rrxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e3_rtxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e3_rtxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e3_rtxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e3_rtxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports e3_rrxc]
set_property IOSTANDARD LVCMOS33 [get_ports e3_rrxdv]
set_property IOSTANDARD LVCMOS33 [get_ports e3_rtxc]
set_property IOSTANDARD LVCMOS33 [get_ports e3_rtxen]
set_property IOSTANDARD LVCMOS33 [get_ports e3_reset]
set_property IOSTANDARD LVCMOS33 [get_ports e3_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports e3_mdc]

set_property PACKAGE_PIN AA14 [get_ports e3_reset]
set_property PACKAGE_PIN Y16 [get_ports e3_mdc]
set_property PACKAGE_PIN Y14 [get_ports e3_mdio]
set_property PACKAGE_PIN W16 [get_ports e3_rrxc]
set_property PACKAGE_PIN U15 [get_ports e3_rrxdv]
set_property PACKAGE_PIN AA17 [get_ports e3_rtxc]
set_property PACKAGE_PIN AA22 [get_ports e3_rtxen]
set_property PACKAGE_PIN U16 [get_ports {e3_rrxd[0]}]
set_property PACKAGE_PIN V14 [get_ports {e3_rrxd[1]}]
set_property PACKAGE_PIN V15 [get_ports {e3_rrxd[2]}]
set_property PACKAGE_PIN AB22 [get_ports {e3_rrxd[3]}]
set_property PACKAGE_PIN AB17 [get_ports {e3_rtxd[3]}]
set_property PACKAGE_PIN V17 [get_ports {e3_rtxd[2]}]
set_property PACKAGE_PIN U17 [get_ports {e3_rtxd[1]}]
set_property PACKAGE_PIN V18 [get_ports {e3_rtxd[0]}]

create_clock -period 8.000 -name e3_rrxc [get_ports e3_rrxc]
set_false_path -reset_path -from [get_clocks sys_clk_in] -to [get_clocks e3_rrxc]

set_property SLEW FAST [get_ports {e3_rtxd[*]}]
set_property SLEW FAST [get_ports e3_rtxen]
set_property SLEW FAST [get_ports e3_rtxc]
# #########################ethernet4###################
set_property IOSTANDARD LVCMOS33 [get_ports {e4_rrxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e4_rrxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e4_rrxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e4_rrxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e4_rtxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e4_rtxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e4_rtxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e4_rtxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports e4_rrxc]
set_property IOSTANDARD LVCMOS33 [get_ports e4_rrxdv]
set_property IOSTANDARD LVCMOS33 [get_ports e4_rtxc]
set_property IOSTANDARD LVCMOS33 [get_ports e4_rtxen]
set_property IOSTANDARD LVCMOS33 [get_ports e4_reset]
set_property IOSTANDARD LVCMOS33 [get_ports e4_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports e4_mdc]

set_property PACKAGE_PIN W17 [get_ports e4_rrxc]
set_property PACKAGE_PIN W18 [get_ports e4_rrxdv]
set_property PACKAGE_PIN AB15 [get_ports e4_rtxc]
set_property PACKAGE_PIN AB14 [get_ports e4_rtxen]
set_property PACKAGE_PIN AB16 [get_ports {e4_rrxd[0]}]
set_property PACKAGE_PIN AA16 [get_ports {e4_rrxd[1]}]
set_property PACKAGE_PIN Y15 [get_ports {e4_rrxd[2]}]
set_property PACKAGE_PIN W15 [get_ports {e4_rrxd[3]}]
set_property PACKAGE_PIN V13 [get_ports {e4_rtxd[0]}]
set_property PACKAGE_PIN W13 [get_ports {e4_rtxd[1]}]
set_property PACKAGE_PIN Y13 [get_ports {e4_rtxd[2]}]
set_property PACKAGE_PIN AA13 [get_ports {e4_rtxd[3]}]
set_property PACKAGE_PIN Y18 [get_ports e4_mdc]
set_property PACKAGE_PIN AA18 [get_ports e4_mdio]
set_property PACKAGE_PIN V19 [get_ports e4_reset]

create_clock -period 8.000 -name e4_rrxc [get_ports e4_rrxc]
set_false_path -reset_path -from [get_clocks sys_clk_in] -to [get_clocks e4_rrxc]

set_property SLEW FAST [get_ports {e4_rtxd[*]}]
set_property SLEW FAST [get_ports e4_rtxen]
set_property SLEW FAST [get_ports e4_rtxc]